// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.mattermost.agenda-plugin",
	Version: "0.1.0",
}
